# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6e5966c9-c12f-4aee-829c-e438b0b11126";
      fsType = "ext4";
    };

  fileSystems."/mnt/claude" =
    { device = "/dev/disk/by-uuid/c08e24d6-636b-465a-87cf-655eaa2e6c3c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/95AE-FDEA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/repos" =
    { device = "/dev/disk/by-uuid/9f9073b1-7f19-496a-a61a-2fc53d8e4e25";
      fsType = "ext4";
    };

  fileSystems."/var/lib/kubelet/pods/64fbca80-7d9c-41a3-bf2d-66d69b6fe494/volumes/kubernetes.io~projected/kube-api-access-9v552" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/cb0d6282-b285-4bed-af37-d75a2ae37acb/volumes/kubernetes.io~projected/kube-api-access-wlvxx" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/362014bc-2c0e-4ef5-a9e3-59876136bc12/volumes/kubernetes.io~projected/kube-api-access-tf4hv" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/9e78f15b-9ae2-40d2-90d1-f2210db611c2/volumes/kubernetes.io~projected/kube-api-access-jpf7r" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/b367be1c-3942-4dcd-9a34-4595548aad96/volumes/kubernetes.io~projected/kube-api-access-fqdq9" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/055fef17-8e1a-4cb8-905e-21ee1fcadee5/volumes/kubernetes.io~projected/kube-api-access-dxbmd" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/6f02f02b-0dbb-4cc3-9e50-9d1c99bb310f/volumes/kubernetes.io~projected/kube-api-access-w29j6" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/13d477bf-a475-49bb-bd00-048034777260/volumes/kubernetes.io~projected/kube-api-access-bjrhl" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/d87a1e65-7135-4934-8e9c-195dc967f0a9/volumes/kubernetes.io~projected/kube-api-access-6gbhs" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/860a2151-43a4-4511-8c14-84a5f5dbf53f/volumes/kubernetes.io~projected/kube-api-access-ljckg" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/var/lib/kubelet/pods/13d477bf-a475-49bb-bd00-048034777260/volumes/kubernetes.io~local-volume/grafana-data" =
    { device = "/mnt/monitoring/grafana";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/kubelet/pods/64fbca80-7d9c-41a3-bf2d-66d69b6fe494/volumes/kubernetes.io~local-volume/loki-data" =
    { device = "/mnt/monitoring/loki";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/kubelet/pods/d87a1e65-7135-4934-8e9c-195dc967f0a9/volumes/kubernetes.io~local-volume/mimir-data" =
    { device = "/mnt/monitoring/mimir";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/kubelet/pods/055fef17-8e1a-4cb8-905e-21ee1fcadee5/volumes/kubernetes.io~local-volume/tempo-data" =
    { device = "/mnt/monitoring/tempo";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.cni0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.flannel.1.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5fbe1c45.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth68262089.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6b16ac76.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha2be9efa.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethae134a81.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb12c4f46.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb81193fd.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethcce4c698.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe4069c97.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
