github_token: ENC[AES256_GCM,data:iIuB6ZvzSBRBqGZvahtLfv+Be2Fvup2vxOwtwXYxOO5Xku3rwA2wOsWPjcVYHG0IbsT5NttRBV5I1EXOroIhwOpU+KK0LRblipvZPqcfVG5+qvLogXO1jmYdV+Hu,iv:2nt0L7Q5rPX24OEafgxjMtlgAMaQXLYodmJV6v8/w/w=,tag:pmLFSmT9s3Ux5fBdnUCEKg==,type:str]
ssh_private_key: ENC[AES256_GCM,data:/BaEv3MfgcVujiDyPU7iU60YA0lHi82EPfFkqn4q9Z60/sHl/eLtYgi3BjuDKQjH09oXNtuSxarlxNHZD070DZxm8Xv2WuYrKrs8dFv+mYUFolI4XFSJ389E1zidEylceXAYiEoak2YnkQIv0MPLPaqUXt2lB7Qdl2cugq2RYIiDID9iL28iab+iCy+CvgTDrihChFuI+Nxp3cYKUQz6HO7kOeJJ0oJmuE4PPkUbdqPdXbfLpSM7994jfT/ya6yX8pbUyu4Mut5TQLLrSutNE5FJlf5X0Pp7DHRUB9dWfmELIWw8VqoutY0c5PRJc+21KSpjfNo6r02B/3sK+8E5h35cpvaYvO8sSVXsjxAsZj0OMUHat3Lx5/eVIDL27MhftM3r+1BepqyxEeDQCDT4Grc0s8yQbXdWzcjy4Vqb4AZG/L/0q81qlJ+7a6Zn2gylfpE4IiDdbP/WrvLiCkqmhFMpF5rsvaytUxz6xeLf8SODwdmVZpwwSjd+lY4Scdn/uKfWnDLb0sVGGYfhd4NZ,iv:U4s3plgjHttMjgfSdvxlnyxKF753xoTfz1fp+PvNVLw=,tag:poTj9CutOqecSwA5Gr7MSw==,type:str]
sops:
    age:
        - recipient: age19psuqagj8ug9tktlajj9kdq94ddyd2uxddrnghxmargpf44zp4qsmxt7n0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb1BxN205UnpUQkh4dkhY
            UllBeEh0c1lBdmtacmV0aWQ3N01xUUVSSkFNCkowR0pRR0lRMEVTY3NRZ0QxajBZ
            UUs5bWRDMHkwYzV0S0F6eHNEdHR2YmMKLS0tIEdScDZIV0FFUEtKRFFpU1FNcW1n
            MittL3orZEpMWWY4cWpjdkRmWTk3T3cKekwJwfPYGJCM5FjQihA4w3n5oYfEzzka
            nqVBdKb7xzBip6N8WEQyTDtNIkxoLZ0RMztxzH9B2m1Yudy31veeyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1689fy0t8umunr826txkg859ym9l7vae94tfjv2v2wea84k9clamqkzke0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUkZqOElqRDg4eTM5RFdV
            NnJQZkR5aG95T2JBa2hOUFkvT0N6RWZMY2lRClAyKzU4ZGpLeG42UnJ6dWFLQVZk
            VEhNT0FlSU4xZ2xyZUVjMzM2QThxNWcKLS0tIHY4TTdVNk5COGNMNWt3b3czc2dR
            RDZXYWRMV2F0OHNOY0FqbXEwK3haVUUKPgPJ2RsXaj1F38eO19FjQE9zJpTk44/g
            c4NPEzcePJso9tNxLuApE45ZR7sjneUa9NaZSUhVwA9PeIzCSkaWKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T21:19:27Z"
    mac: ENC[AES256_GCM,data:Os4zwLBggLOpSgPn0veSxsWbiwY/Jo18N9da+q1E1qvgPGTKnx8uBXG8w+VRYY0mooRuxiIsXqlXCPVh8xPnBwWAF+k/8YJBTbL/NoIN/oJWppfCOUyloNkfKlvNpLRJOAkSJyxpwar/ILG1/FF7KlvWBuNgDl9yp1zg7AqDyCo=,iv:RPYoZYjT2mbwQ9OZvbPxMG5EiDcroSBHzPbEXUKY2dE=,tag:Top203tweyIITJm4NCNUFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
